[tool.isort]
profile = "hug"
src_paths = ["isort", "tests"]

[tool.yapf]
based_on_style = "google"
indent_width = 4
column_limit = 100
spaces_before_comment = 4
split_before_logical_operator = true

[tool.yapfignore]
ignore_patterns = [
  "temp/**/*.py",
  "temp2/*.py"
]
